[package]
name = "deno_desktop"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
deno_runtime = { git = "https://github.com/DjDeveloperr/deno.git", branch = "ext-webgpu-public" }
winit-main = { version = "0.1.1", features = ["proc"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4.0"
serde = { version = "1", features = ["derive"] }
wgpu-core = { version = "0.10.1", features = ["raw-window-handle"] }
